version: "3.0"
services:
  application:
    image: springboot-app
    networks:
      - springboot-db-net
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "ordermanagement"
    volumes:
      - app_data:/var/lib/mysql

networks:
  springboot-db-net:

volumes:
  app_data:
