spring:
datasource:
url: jdbc:mysql://mysqldb:3306/ordermanagement?useSSL=false
username: root
password: test
jpa:
properties:
hibernate:
dialect: org.hibernate.dialect.MySQL5Dialect
hibernate.globally_quoted_identifiers: true
hibernate.ddl-auto: update
hibernate.show_sql: true
hibernate.format_sql: true
logging:
level:
org.hibernate.SQL: debug
